#' Report Manager Module
#'
#' @details
#' This module supports collaborative work on `teal` reports, generated by `teal.reporter`
#' package. This module extends functionalities of `teal.reporter` and allows to store
#' reports in chosen path. Reports will be stored as JSON files inside folders named after
#' reports.
#'
#' @param reports_path character. Absolute path where reports should be stored.
#' @param auto_save logical. Whether to save active report whenever there are any changes made.
#'
#' @importFrom teal module
#'
#' @examples
#'
#' app <- teal::init(
#'   data = teal.data::teal_data(IRIS = iris),
#'   modules = teal::modules(
#'     teal::example_module(transformators = list(or_filtering_transformator("IRIS"))),
#'     tm_report_manager()
#'   )
#' )
#' if (interactive()) {
#'   shinyApp(app$ui, app$server)
#' }
#' @export
tm_report_manager <- function(
  reports_path = "reports",
  auto_save = TRUE
) {
  module(
    ui = report_manager_ui,
    server = report_manager_server,
    label = "Report Manager",
    server_args = list(
      reports_path = reports_path,
      auto_save = auto_save
    )
  )
}

#' The `UI` of [`tm_report_manager()`]
#'
#' @param id (`character`) the id of the module.
#' @importFrom DT DTOutput
#' @import shiny
#'
#' @keywords internal
report_manager_ui <- function(id) {
  ns <- NS(id)
  tagList(
    tags$style(HTML("
      .dt_highlight{ background-color: #eb1700 !important; color: #ffffff !important;}

      /* Badge that appears on hover for highlighted rows only */
    .current_report_badge {
      display: none;
      margin-left: 6px;
      font-size: 0.75em;
      vertical-align: middle;
    }

    /* Action buttons spacing */
    .dataTables_wrapper .btn {
      margin-right: 3px;
    }

    /* Tooltip styling */
    .tooltip {
      font-size: 12px;
    }

    /* Enable text wrapping in table cells */
    table.dataTable td {
      white-space: normal;
      word-wrap: break-word;
    }
    ")),
    fluidRow(
      column(4,
        style = "text-align: left;",
        actionButton(ns("show_help"), "Help", icon = icon("question-circle"), class = "btn-info btn-sm"),
        actionButton(ns("merge_reports"), "Merge reports"),
        actionButton(ns("create_new_report_btn"), "Create new report", icon = icon("plus"), class = "btn-success")
      )
    ),
    br(),
    # List of reports
    DT::DTOutput(ns("report_list"), width = "75%"),
    tags$script(HTML(paste0("
    $(document).on('click', '.release-lock-btn', function() {
      var reportName = $(this).data('report');
      Shiny.setInputValue('", ns("release_lock_click"), "', reportName, {priority: 'event'});
    });
  ")))
  )
}

#' The server part of [`tm_report_manager()`].
#'
#' @inheritParams tm_report_manager
#' @inheritParams report_manager_ui
#' @param reporter the object that holds the report. Provided by `teal`.
#' @import shiny teal
#' @importFrom DT renderDT
#' @importFrom shinyjs toggleState disable enable
#' @keywords internal
report_manager_server <- function(id, reports_path = "reports", auto_save = TRUE, reporter) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    # Initialize shinyjs
    shinyjs::useShinyjs()

    # Initialize report manager object
    rm <- ReportManager$new(reports_path = reports_path, session)
    if (auto_save) {
      rm$auto_save_observer(reporter)
    }

    # reactiveVals
    delete_candidate <- reactiveVal(NULL)
    rebuild_candidate <- reactiveVal(NULL)
    load_candidate <- reactiveVal(NULL)
    edit_candidate <- reactiveVal(NULL)
    release_candidate <- reactiveVal(NULL)
    refresh_trigger <- reactiveVal(Sys.time())
    modal_shown <- reactiveVal(FALSE)

    # Helper functions
    validate_title <- function(title) {
      !is.null(title) && nzchar(trimws(title))
    }

    refresh_ui <- function() {
      refresh_trigger(Sys.time())
      shinyjs::toggleState("merge_reports", condition = !is.null(rm$current_report_title()))
    }

    handle_error <- function(action, err) {
      showNotification(sprintf("Error %s: %s", action, conditionMessage(err)), type = "error")
    }

    create_action_button <- function(action, report_name, icon, btn_class, title) {
      safe_name <- gsub("'", "\\'", report_name)
      sprintf(
        paste0(
          '<button type="button" class="btn btn-sm %s" onclick="Shiny.setInputValue(\'%s\', \'%s\', ',
          '{priority: \'event\'})" title="%s" data-toggle="tooltip"><i class="fa fa-%s"></i></button>'
        ),
        btn_class, ns(action), safe_name, title, icon
      )
    }

    # Initially disable merge button and trigger initial load
    shinyjs::disable("merge_reports")
    observe(
      {
        rm$list_reports()
        refresh_trigger(Sys.time())
      },
      priority = 1000
    )

    # Monitor reporter cards for new report creation
    observe({
      cards_count <- length(reporter$get_cards())
      current_title <- rm$current_report_title()

      # If cards exist but no current report and modal not shown, show modal
      if (is.null(current_title) && cards_count > 0 && !modal_shown()) {
        modal_shown(TRUE)
        showModal(modalDialog(
          title = "Create New Report",
          "You are creating a new report. Please enter a report title:",
          textInput(ns("new_report_title"), "Report title:", value = ""),
          footer = tagList(
            modalButton("Cancel"),
            actionButton(ns("create_new_report"), "Create Report")
          ),
          easyClose = FALSE
        ))
      }

      # Reset flag when no cards
      if (cards_count == 0) {
        modal_shown(FALSE)
      }
    })

    observeEvent(input$create_new_report, {
      new_title <- trimws(input$new_report_title)
      removeModal()
      modal_shown(FALSE)

      if (!validate_title(new_title)) {
        showNotification("Report title cannot be empty.", type = "error")
        return()
      }

      tryCatch(
        {
          rm$create_new_report(new_title, reporter)
          rm$list_reports()
          refresh_ui()
          showNotification(sprintf("Created new report: %s", new_title), type = "message")
        },
        error = function(err) handle_error("creating report", err)
      )
    })

    # Manual create new report button
    observeEvent(input$create_new_report_btn, {
      showModal(modalDialog(
        title = "Create New Report",
        "Enter a title for the new report. Current report will be saved automatically.",
        textInput(ns("manual_new_report_title"), "Report title:", value = ""),
        footer = tagList(
          modalButton("Cancel"),
          actionButton(ns("confirm_create_new_report"), "Create Report")
        ),
        easyClose = FALSE
      ))
    })

    observeEvent(input$confirm_create_new_report, {
      new_title <- trimws(input$manual_new_report_title)
      removeModal()

      if (!validate_title(new_title)) {
        showNotification("Report title cannot be empty.", type = "error")
        return()
      }

      tryCatch(
        {
          rm$create_new_report(new_title, reporter)
          rm$list_reports()
          refresh_ui()
          showNotification(sprintf("Created new report: %s", new_title), type = "message")
        },
        error = function(err) handle_error("creating report", err)
      )
    })

    # Help modal
    observeEvent(input$show_help, {
      showModal(modalDialog(
        title = "Report Permissions",
        HTML("
          <h4>Permissions Summary:</h4>
          <table class='table table-bordered table-sm' style='margin-top: 10px;'>
            <thead>
              <tr>
                <th>Action</th>
                <th>Active Report</th>
                <th>Your Locked Report</th>
                <th>Others' Locked Report</th>
                <th>Unlocked Report</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Edit Title</strong></td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #f8d7da;'>No</td>
                <td style='background-color: #f8d7da;'>No</td>
              </tr>
              <tr>
                <td><strong>Delete</strong></td>
                <td style='background-color: #f8d7da;'>No</td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #f8d7da;'>No</td>
                <td style='background-color: #d4edda;'>Yes</td>
              </tr>
              <tr>
                <td><strong>Rebuild</strong></td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #d4edda;'>Yes</td>
              </tr>
              <tr>
                <td><strong>Load/View</strong></td>
                <td style='background-color: #fff3cd;'>Already active</td>
                <td style='background-color: #d4edda;'>Full access</td>
                <td style='background-color: #d1ecf1;'>View only</td>
                <td style='background-color: #d1ecf1;'>View only</td>
              </tr>
              <tr>
                <td><strong>Release Lock</strong></td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #d4edda;'>Yes</td>
                <td style='background-color: #f8d7da;'>No</td>
                <td style='background-color: #e2e3e5;'>N/A</td>
              </tr>
              <tr>
                <td><strong>Merge</strong></td>
                <td style='background-color: #d4edda;'>Yes*</td>
                <td style='background-color: #d4edda;'>Yes*</td>
                <td style='background-color: #d4edda;'>Yes*</td>
                <td style='background-color: #d4edda;'>Yes*</td>
              </tr>
            </tbody>
          </table>
          <p style='font-size: 0.9em; margin-top: 5px;'>
            <em>* Merge requires reports to have saved content (cards)</em>
          </p>
        "),
        size = "l",
        footer = modalButton("Close"),
        easyClose = TRUE
      ))
    })

    # Release lock by clicking on lock icon
    observeEvent(input$release_lock_click, {
      release_candidate(input$release_lock_click)
      showModal(modalDialog(
        title = "Release Lock",
        sprintf(
          paste0(
            "Are you sure you want to release your lock on '%s'?",
            "The report will remain loaded but become read-only for you."
          ),
          input$release_lock_click
        ),
        footer = tagList(
          modalButton("Cancel"),
          actionButton(ns("confirm_release_lock"), "Yes, release lock")
        ),
        easyClose = FALSE
      ))
    })

    observeEvent(input$confirm_release_lock, {
      removeModal()
      report_name <- release_candidate()
      if (!validate_title(report_name)) {
        showNotification("No report selected to release lock.", type = "error")
        return()
      }

      withProgress(message = "Releasing lock...", value = 0.3, {
        tryCatch(
          {
            rm$release_lock(report_name)
            refresh_trigger(Sys.time())
          },
          error = function(err) handle_error("releasing lock", err)
        )
        incProgress(0.7)
      })
    })

    # Refresh button handler
    observeEvent(input$refresh_report_list, {
      tryCatch(
        {
          rm$list_reports()
          refresh_ui()
          showNotification("Report list refreshed", type = "message")
        },
        error = function(err) handle_error("refreshing list", err)
      )
    })

    output$report_list <- DT::renderDT({
      # Depend on refresh trigger and the current report title to ensure updates
      refresh_trigger()
      current_title <- rm$current_report_title()

      # Also depend on the reporter cards to trigger refresh when new cards are added
      reporter$get_cards()

      df <- rm$available_reports()
      if (is.null(df) || nrow(df) == 0) {
        df <- data.frame(
          reports = character(0),
          created_by = character(0),
          locked_by = character(0),
          last_rebuild = character(0),
          stringsAsFactors = FALSE
        )
      }

      # Ensure all required columns exist
      if (!"reports" %in% names(df)) df$reports <- character(0)
      if (!"created_by" %in% names(df)) df$created_by <- character(0)
      if (!"locked_by" %in% names(df)) df$locked_by <- character(0)
      if (!"last_rebuild" %in% names(df)) df$last_rebuild <- character(0)

      # Ensure 'reports' is character
      df$reports <- as.character(df$reports)

      # If current report exists but not in df, add it
      if (!is.null(current_title) && nzchar(as.character(current_title))) {
        if (length(df$reports) == 0 || !any(df$reports == as.character(current_title))) {
          user_name <- ifelse(interactive(), Sys.getenv("USER"), session$user)
          if (is.null(user_name) || user_name == "") user_name <- "Current User"

          current_locked_by <- if (!is.null(rm$my_locked_report) &&
            rm$my_locked_report == as.character(current_title)) {
            user_name
          } else {
            ""
          }

          new_row <- data.frame(
            reports = as.character(current_title),
            created_by = user_name,
            locked_by = current_locked_by,
            last_rebuild = "Never",
            stringsAsFactors = FALSE
          )
          df <- rbind(new_row, df)
        }
      }

      # Format columns for display
      df$locked_by <- ifelse(is.na(df$locked_by) | df$locked_by == "", "", as.character(df$locked_by))
      df$created_by <- ifelse(is.na(df$created_by) | df$created_by == "", "", as.character(df$created_by))
      df$last_rebuild <- ifelse(is.na(df$last_rebuild) | df$last_rebuild == "", "Never", as.character(df$last_rebuild))

      # Add status HTML column with Active/Locked/Unlocked logic
      if (nrow(df) > 0) {
        df$status <- vapply(seq_len(nrow(df)), function(i) {
          report_name <- as.character(df$reports[i])
          locked_by_val <- as.character(df$locked_by[i])
          is_locked <- !is.na(locked_by_val) && nzchar(locked_by_val)

          if (!is.null(current_title) && identical(report_name, as.character(current_title))) {
            '<span class="label label-success">Active</span>'
          } else if (is_locked) {
            '<span class="label label-warning">Locked</span>'
          } else {
            '<span class="label label-default">Unlocked</span>'
          }
        }, character(1))
      } else {
        df$status <- character(0)
      }

      # Add combined Actions column with icons and tooltips
      if (nrow(df) > 0) {
        df$actions <- vapply(seq_len(nrow(df)), function(i) {
          report_name <- as.character(df$reports[i])
          locked_by_val <- as.character(df$locked_by[i])
          is_locked <- !is.na(locked_by_val) && nzchar(locked_by_val)
          is_active <- !is.null(current_title) && identical(report_name, as.character(current_title))

          # Lock status icon (first in actions)
          is_my_lock <- !is.null(rm$my_locked_report) && rm$my_locked_report == report_name
          if (is_locked) {
            if (is_my_lock) {
              # Clickable lock for user's own locks
              lock_icon <- sprintf(
                paste0(
                  '<i class="fa fa-lock release-lock-btn" style="color: red; ',
                  'margin-right: 8px; cursor: pointer;" title="Click to release your lock" data-report="%s"></i>'
                ),
                report_name
              )
            } else {
              # Non-clickable lock for others' locks
              lock_icon <- paste0(
                '<i class="fa fa-lock" style="color: red; ',
                'margin-right: 8px;" title="Locked by another user"></i>'
              )
            }
          } else {
            lock_icon <- '<i class="fa fa-unlock" style="color: green; margin-right: 8px;" title="Unlocked"></i>'
          }

          # Action buttons based on state
          if (is_active) {
            # Active report: can edit title, cannot delete, can rebuild
            edit_btn <- create_action_button("edit_row", report_name, "edit", "btn-warning", "Edit report title")
            load_btn <- paste0(
              '<button type="button" class="btn btn-sm btn-secondary" ',
              'disabled title="Already active" data-toggle="tooltip"><i class="fa fa-check"></i></button>'
            )
            rebuild_btn <- create_action_button(
              "rebuild_row",
              report_name, "refresh", "btn-primary", "Rebuild report with new data"
            )
            delete_btn <- paste0(
              '<button type="button" class="btn btn-sm btn-secondary" ',
              'disabled title="Cannot delete active report" data-toggle="tooltip"><i class="fa fa-ban"></i></button>'
            )
          } else if (is_locked) {
            if (is_my_lock) {
              # My locked report: can edit, load, rebuild, delete
              edit_btn <- create_action_button("edit_row", report_name, "edit", "btn-warning", "Edit report title")
              load_btn <- create_action_button("load_row", report_name, "download", "btn-success", "Load this report")
              rebuild_btn <- create_action_button(
                "rebuild_row", report_name, "refresh", "btn-primary", "Rebuild report with new data"
              )
              delete_btn <- create_action_button(
                "delete_report", report_name, "trash", "btn-danger", "Delete this report"
              )
            } else {
              # Others' locked report: can view and rebuild, cannot edit/delete
              edit_btn <- paste0(
                '<button type="button" class="btn btn-sm btn-secondary" ',
                'disabled title="Report locked by another user" ',
                'data-toggle="tooltip"><i class="fa fa-ban"></i></button>'
              )
              load_btn <- create_action_button(
                "load_row", report_name, "eye", "btn-info", "View this report (read-only)"
              )
              rebuild_btn <- create_action_button(
                "rebuild_row", report_name, "refresh", "btn-primary", "Rebuild report with new data"
              )
              delete_btn <- paste0(
                '<button type="button" class="btn btn-sm btn-secondary" ',
                'disabled title="Report locked by another user" data-toggle="tooltip"><i class="fa fa-ban"></i>',
                "</button>"
              )
            }
          } else {
            # Unlocked report: can view, delete, and rebuild, cannot edit
            edit_btn <- paste0(
              '<button type="button" class="btn btn-sm btn-secondary" ',
              'disabled title="Report is unlocked" data-toggle="tooltip"><i class="fa fa-ban"></i></button>'
            )
            load_btn <- create_action_button("load_row", report_name, "eye", "btn-info", "View this report")
            rebuild_btn <- create_action_button(
              "rebuild_row", report_name, "refresh", "btn-primary", "Rebuild report with new data"
            )
            delete_btn <- create_action_button(
              "delete_report", report_name, "trash", "btn-danger", "Delete this report"
            )
          }

          # Combine all elements with spacing
          paste(lock_icon, edit_btn, load_btn, rebuild_btn, delete_btn, sep = " ")
        }, character(1))
      } else {
        df$actions <- character(0)
      }

      # Rename columns for display
      colnames(df) <- c("Report Title", "Created by", "Locked by", "Last Rebuild", "Status", "Actions")

      # Render the datatable
      DT::datatable(
        df,
        escape = FALSE,
        selection = "single",
        rownames = FALSE,
        options = list(
          pageLength = 10,
          autoWidth = TRUE,
          searching = FALSE,
          lengthChange = FALSE,
          initComplete = DT::JS(
            "function(settings, json) {",
            "  $('[data-toggle=\"tooltip\"]').tooltip();",
            "}"
          ),
          drawCallback = DT::JS(
            "function(settings) {",
            "  $('[data-toggle=\"tooltip\"]').tooltip();",
            "}"
          ),
          rowCallback = DT::JS(
            "function(row, data, index){",
            "  $('[data-toggle=\"tooltip\"]').tooltip();",
            "}"
          )
        )
      )
    })

    # Merge reports button handler
    observeEvent(input$merge_reports, {
      avail_reports <- rm$available_reports()
      current <- rm$current_report_title()

      # Filter reports that have Report.json (have content)
      reports_with_content <- character(0)
      for (report in avail_reports$reports) {
        report_json <- file.path(rm$get_abs_report_path(report), "Report.json")
        if (file.exists(report_json)) {
          reports_with_content <- c(reports_with_content, report)
        }
      }

      if (length(reports_with_content) < 2) {
        showNotification("Need at least 2 reports with content to merge.", type = "error")
        return()
      }

      showModal(
        modalDialog(
          title = "Merge Reports",
          checkboxGroupInput(
            inputId = ns("merge_select"),
            label = "Select reports to merge (select 2 or more):",
            choices = reports_with_content,
            selected = if (!is.null(current) && current %in% reports_with_content) current else NULL
          ),
          textInput(ns("merged_report_title"), "New merged report title:", value = ""),
          footer = tagList(
            modalButton("Cancel"),
            actionButton(ns("confirm_merge"), "Merge reports")
          )
        )
      )
    })

    observeEvent(input$confirm_merge, {
      removeModal()
      selected_reports <- input$merge_select
      new_title <- trimws(input$merged_report_title)

      if (length(selected_reports) < 2) {
        showNotification("Please select at least 2 reports to merge.", type = "error")
        return()
      }

      if (!validate_title(new_title)) {
        showNotification("Merged report title cannot be empty.", type = "error")
        return()
      }

      withProgress(message = "Merging reports...", value = 0.3, {
        tryCatch(
          {
            # Load first report as base
            rm$load_report(selected_reports[1], reporter)

            # Merge remaining reports into it
            for (i in 2:length(selected_reports)) {
              rm$merge_reports(selected_reports[1], selected_reports[i], reporter)
            }

            # Rename to new title
            rm$rename_report(selected_reports[1], new_title, reporter)

            # Delete original reports except the first one (now renamed)
            for (report in selected_reports[-1]) {
              rm$delete_report(report)
            }

            refresh_ui()
            showNotification(
              sprintf("Successfully merged %d reports into '%s'", length(selected_reports), new_title),
              type = "message"
            )
          },
          error = function(err) handle_error("merging reports", err)
        )
        incProgress(0.7)
      })
    })

    # ---- Row button handlers (delete / rebuild / load / edit) ----

    # Edit row clicked -> show edit modal
    observeEvent(input$edit_row, {
      edit_candidate(input$edit_row)
      showModal(modalDialog(
        title = "Edit Report Title",
        textInput(ns("new_report_title"), "New report title:", value = input$edit_row),
        footer = tagList(
          modalButton("Cancel"),
          actionButton(ns("confirm_edit"), "Save")
        ),
        easyClose = FALSE
      ))
    })

    observeEvent(input$confirm_edit, {
      removeModal()
      old_title <- edit_candidate()
      new_title <- trimws(input$new_report_title)

      if (!validate_title(new_title)) {
        showNotification("Report title cannot be empty.", type = "error")
        return()
      }

      if (old_title == new_title) {
        return()
      }

      withProgress(message = "Renaming report...", value = 0.2, {
        tryCatch(
          {
            rm$rename_report(old_title, new_title, reporter)
            refresh_ui()
            showNotification(sprintf("Renamed report from '%s' to '%s'", old_title, new_title), type = "message")
          },
          error = function(err) handle_error("renaming report", err)
        )
        incProgress(0.8)
      })
    })

    # Delete row clicked -> show confirm modal
    observeEvent(input$delete_report, {
      delete_candidate(input$delete_report)
      showModal(modalDialog(
        title = "Are you sure you want to delete this report?",
        footer = tagList(
          modalButton("Cancel"),
          actionButton(ns("final_delete"), "Yes, delete report")
        ),
        easyClose = FALSE
      ))
    })

    observeEvent(input$final_delete, {
      removeModal()
      report_name <- delete_candidate()
      if (!validate_title(report_name)) {
        showNotification("No report selected to delete.", type = "error")
        return()
      }

      current_title <- rm$current_report_title()
      if (!is.null(current_title) && identical(as.character(report_name), as.character(current_title))) {
        showNotification("Cannot delete the currently active report.", type = "error")
        return()
      }

      withProgress(message = "Deleting report...", value = 0.3, {
        tryCatch(
          {
            rm$delete_report(report_name)
            refresh_ui()
            showNotification(sprintf("Deleted report: %s", report_name), type = "message")
          },
          error = function(err) handle_error("deleting report", err)
        )
        incProgress(0.7)
      })
    })

    # Rebuild row clicked -> show confirm modal
    observeEvent(input$rebuild_row, {
      rebuild_candidate(input$rebuild_row)
      showModal(modalDialog(
        title = "Are you sure you want to rebuild the report with new data?",
        "Unsaved changes to the report will be lost",
        footer = tagList(
          modalButton("Cancel"),
          actionButton(ns("confirm_rebuild"), "Yes, rebuild")
        ),
        easyClose = FALSE
      ))
    })

    observeEvent(input$confirm_rebuild, {
      removeModal()
      report_id <- rebuild_candidate()
      if (!validate_title(as.character(report_id))) {
        showNotification("No report selected to rebuild.", type = "error")
        return()
      }
      withProgress(message = "Rebuilding report...", value = 0.2, {
        tryCatch(
          {
            rm$rebuild_report(report_id, rp = reporter)
            refresh_ui()
            showNotification(sprintf("Rebuild started for report: %s", report_id), type = "message")
          },
          error = function(err) {
            handle_error("rebuilding report", err)
            message("Rebuild error for report: ", report_id)
            message(conditionMessage(err))
          }
        )
        incProgress(0.8)
      })
    })

    # Load row clicked -> confirm and call load
    observeEvent(input$load_row, {
      load_candidate(input$load_row)
      report_name <- input$load_row

      # Check if this is a locked report by someone else or unlocked
      avail_reports <- rm$available_reports()
      report_row <- avail_reports[avail_reports$reports == report_name, ]
      locked_by_val <- if (nrow(report_row) > 0) report_row$locked_by else ""
      is_locked <- !is.na(locked_by_val) && nzchar(locked_by_val)
      is_my_lock <- !is.null(rm$my_locked_report) && rm$my_locked_report == report_name

      if (is_locked && !is_my_lock) {
        # Others' locked report - view only
        showModal(modalDialog(
          title = "View Report (Read-Only)",
          "This report is locked by another user. You can view it but cannot make changes. Do you want to continue?",
          footer = tagList(
            modalButton("Cancel"),
            actionButton(ns("confirm_view_report"), "Yes, view report")
          ),
          easyClose = FALSE
        ))
      } else {
        # My locked report or can be locked - full access
        showModal(modalDialog(
          title = "Load report",
          "Unsaved changes to the current report will be lost. Do you want to load this report?",
          footer = tagList(
            modalButton("Cancel"),
            actionButton(ns("confirm_load_row"), "Yes, load report")
          ),
          easyClose = FALSE
        ))
      }
    })

    observeEvent(input$confirm_view_report, {
      removeModal()
      report_name <- load_candidate()
      if (!validate_title(report_name)) {
        showNotification("No report selected to view.", type = "error")
        return()
      }
      withProgress(message = "Loading report (read-only)...", value = 0.2, {
        tryCatch(
          {
            # Load report without locking (read-only mode)
            rm$load_report(report_name, reporter, skip_lock = TRUE)
            refresh_ui()
            showNotification(sprintf("Loaded report in read-only mode: %s", report_name), type = "message")
          },
          error = function(err) handle_error("loading report", err)
        )
        incProgress(0.8)
      })
    })

    observeEvent(input$confirm_load_row, {
      removeModal()
      report_name <- load_candidate()
      if (!validate_title(report_name)) {
        showNotification("No report selected to load.", type = "error")
        return()
      }
      withProgress(message = "Loading report...", value = 0.2, {
        tryCatch(
          {
            rm$load_report(report_name, reporter)
            refresh_ui()
            showNotification(sprintf("Loaded report: %s", report_name), type = "message")
          },
          error = function(err) handle_error("loading report", err)
        )
        incProgress(0.8)
      })
    })

    # Insert Refresh button once
    onFlushed(function() {
      insertUI(
        selector = "#teal-teal_modules-nav-report_manager-wrapper > div:nth-child(1) > div:nth-child(2)",
        where = "afterBegin",
        ui = tags$div(
          id = ns("refresh_report_btn_wrapper"),
          actionButton(ns("refresh_report_list"), "Refresh list", class = "btn-primary")
        )
      )
    }, once = TRUE)
  })
}
